services:
  mysql:
    image: mysql:8.1.0
    container_name: TNTV-data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5ang15122003
      MYSQL_DATABASE: TNTV_web
      MYSQL_USER: user
      MYSQL_PASSWORD: test123
    ports:
      - "3333:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: TNTV-backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "7777:7777"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=test123  
      - MYSQL_DB=TNTV_web
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
